cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    gladys:
      email: gladys@gmail.com
      name: gladys
      password: $2b$12$k/EYgyTV5Cl9DLwVFnT9xOge3I8KEowJBn9U2B3Hbe3WLz2BWGlfa
    kingk:
      email: jose@gmail.com
      name: J alex P
      password: $2b$12$uzxNMFLP2Q/3kXqZAk.p.OdJ5zLAv1LCA.xvQGlpISSPyaGikEajm
preauthorized:
  emails:
  - mawarni@gmail.com
  - alexandre@gmail.com
